org: delorenj
app: summaraize
service: summaraize
frameworkVersion: '3'

package:
  individually: true

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: us-east-1
  environment:
    OPENAI_API_KEY: ${param:openaiApiKey}
    booksTableName: ${self:custom.booksTableName}
    usersTableName: ${self:custom.usersTableName}
    stripeSecretKey: ${param:stripeSecretKey}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      # Restrict our IAM role permissions to
      # the specific table for the stage
      Resource:
        - "Fn::GetAtt": [ BooksTable, Arn ]
        - "Fn::GetAtt": [ UsersTable, Arn ]

plugins:
  - serverless-bundle
  - serverless-s3-local
  - serverless-offline
custom:
  stage: ${opt:stage, self:provider.stage}
  booksTableName: ${self:custom.stage}-books
  usersTableName: ${self:custom.stage}-users


resources:
  - ${file(resources/api-gateway-errors.yml)}
  - ${file(resources/dynamodb-table.yml)}
  - ${file(resources/s3.yml)}
  - ${file(resources/cognito-authorizer.yml)}
#  - ${file(resources/cognito-user-pool.yml)}
#  - ${file(resources/cognito-identity-pool.yml)}

functions:
#  proxy_function:
#    handler: proxy.handler
#    events:
#      - http:
#          path: /{proxy+}
#          method: ANY

  parseBookMetadata:
    handler: book.parseBookMetadata
    events:
      - http:
          path: /book/metadata
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer
  getUserData:
    handler: user.getData
    events:
      - http:
          path: /user
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId:
              Ref: ApiGatewayAuthorizer

  summarizeChunk:
    handler: summarize.summarizeChunk
    events:
      - http:
          path: /sc
          method: get
          authorizer: aws_iam

  create:
    handler: create.main
    events:
      - http:
          path: notes
          cors: true
          method: post
          authorizer: aws_iam

  billing:
    handler: billing.main
    events:
      - http:
          path: billing
          cors: true
          method: post
          authorizer: aws_iam
